apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  labels:
    app: webgoat
spec:
  type: LoadBalancer # Exposes the service externally
  ports:
  - port: 8080       # External port for 8080
    targetPort: 8080 # Container port
    protocol: TCP
  - port: 9090       # External port for 9090
    targetPort: 9090 # Container port
    protocol: TCP
  selector:
    app: webgoat
